version: '3.8'

services:
  # Frontend services
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - dialog_manager

  # Backend services
  intent_service:
    build: ./backend/intent_service
    ports:
      - "8001:8000"
    volumes:
      - ./backend/intent_service:/app
    environment:
      - LOG_LEVEL=INFO
    depends_on:
      - redis

  dialog_manager:
    build: ./backend/dialog_manager
    ports:
      - "8000:8000"
    volumes:
      - ./backend/dialog_manager:/app
      - /app/node_modules
    environment:
      - INTENT_SERVICE_URL=http://intent_service:8000
      - RAG_SERVICE_URL=http://rag_service:8000
      - REDIS_URL=redis://redis:6379
    depends_on:
      - intent_service
      - rag_service
      - redis

  rag_service:
    build: ./backend/rag_service
    ports:
      - "8002:8000"
    volumes:
      - ./backend/rag_service:/app
      - ./data:/data
    environment:
      - LOG_LEVEL=INFO
    depends_on:
      - redis

  # Infrastructure services
  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=chatbot
      - POSTGRES_PASSWORD=chatbot_pass
      - POSTGRES_DB=chatbot_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  redis_data:
  postgres_data:
